name: Build Corydora

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set QMK home
        run: qmk setup -H $GITHUB_WORKSPACE --yes

      - name: Compile firmware
        working-directory: ${{ github.workspace }}
        run: qmk compile -kb handwired/corydora -km default

      - uses: actions/upload-artifact@v4
        with:
          name: corydora-uf2
          path: |
            *.uf2
            .build/*.uf2
